"""Add LLM model field to Generation class

Revision ID: a0318327cfbb
Revises: 5845a6a202dc
Create Date: 2023-03-19 09:54:45.844733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0318327cfbb'
down_revision = '5845a6a202dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.Enum('gpt3', 'gpt4', name='modeltypes'), server_default='gpt3', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
